import { computed, ref } from 'vue'
import { defineStore } from 'pinia'
import { db } from '@/firebase'
import { arrayRemove, arrayUnion, collection, deleteDoc, doc, serverTimestamp, setDoc, updateDoc } from "firebase/firestore"
import { useUserAccess } from './access/userAccess'
import { useFirestore } from '@vueuse/firebase/useFirestore'

/*
   User
      id - generated by auth
      email - read/only - from auth
      firstName
      lastName
      username
      images
         ...itemImage
      settings
         itemHeaders[]
         galleryThumbOptions[]
         itemThumbOptions[]
         searches[]
         showHiddenItems
         notifyViaEmail
         notifyViaMessage
         soloMode - boolean, initially false
      messagingTokens[]
         device
         token
      dateVisited
      dateCreated
      dateModified
*/
const USER_TABLE = 'users'

export const useUserStore = defineStore('user', () => {
   const userAccess = useUserAccess()
   const userCollection = collection(db, USER_TABLE)
   function userDoc(id)  { return doc(db, USER_TABLE, id) }
   
   const addListener    = async () => { userAccess.addListener() } 
   const removeListener = async () => { userAccess.removeListener() }
   
   // const users = useFirestore(userCollection)   
   const users = computed(() => userAccess.users)
   const userIdToUser = computed(() => { return users.value ? new Map(users.value.map((obj) => [obj.id, obj])) : new Map() })
   const usernames    = computed(() => new Set(users.value.map(obj => obj.username)) )
   
   const userId = ref('')
   // const userQuery = computed(() => userId.value && userDoc(userId.value))
   // const user = useFirestore(userQuery, null)
   const user       = computed(() => userId.value && getUser(userId.value))
   const userExists = computed(() => user.value ? true : false)
   
   function getUser(id) { return userIdToUser.value.get(id) }
   function getUsername(id) { return userIdToUser.value.has(id) ? userIdToUser.value.get(id).username : "" }

   function setUser(user) {
      console.log("setUser", user) 
      userId.value = user.id
      const userToSet = { ...user, dateCreated: serverTimestamp(), dateModified: serverTimestamp() }
      setDoc(userDoc(userToSet.id), userToSet)
   }

   function addProfileUser(user) {
      console.log("addProfileUser", user) 
      const newUserRef = doc(userCollection) // generate a firebase id, which looks like other userIds
      const newUser = { ...user, id: newUserRef.id, dateCreated: serverTimestamp(), dateModified: serverTimestamp() }
      setDoc(newUserRef, newUser)
      return newUser
   }

   function updateDateVisited(userId) { 
      console.log("updateDateVisited", userId) 
      updateUser({ id:userId, dateVisited:serverTimestamp() }) }
   
   function updateUser(updatedUser) {
      console.log("updateUser", updatedUser) 
      const userToUpdate = { ...updatedUser, dateModified: serverTimestamp() }
      updateDoc(userDoc(userToUpdate.id), userToUpdate)
   }

   const myFullName = computed(() => user.value ? (user.value.firstName ? user.value.firstName + " ": "") + user.value.lastName : "")
   const mySettings = computed(() => user.value && user.value.settings ? user.value.settings : {} )
   const soloMode   = computed(() => mySettings.value?.soloMode)

   function updateSettings(settings) {
      updateDoc(userDoc(userId.value), { 
         settings: settings,
         dateModified: serverTimestamp(),
      })
   }

   function deleteUser(id) {
      // console.log("deleteUser", id) 
      // backend cleans up items/groups/galleries/wall and deletes user from auth
      deleteDoc(doc(userCollection, id))
   }

   //
   // user images
   //
   function addImage(image) {
      if (user.value.images) { 
           updateDoc(userDoc(userId.value), { images:arrayUnion(image), dateModified:serverTimestamp() })
      }
      else { updateImages([ images ])  }
   }

   function removeImage(image) {
      updateDoc(userDoc(userId.value), { images:arrayRemove(image), dateModified:serverTimestamp() })
   }

   function updateImage(updatedImage) {
      const images = []
      for (const image of user.value.images) {
         images.push(image.id == updatedImage.id ? updatedImage : image)
      }
      updateDoc(userDoc(userId.value), { images: images, dateModified: serverTimestamp() })
   }

   function updateImages(images) {
      updateDoc(userDoc(userId.value), { images: images, dateModified: serverTimestamp() })
   }

   return { 
      users, addListener, removeListener,
      userId, user, userIdToUser, usernames, userExists, getUser, getUsername, 
      setUser, addProfileUser, updateDateVisited, updateUser, deleteUser,
      myFullName, mySettings, soloMode, updateSettings, addImage, removeImage, updateImage, updateImages
   }
})
